### ISSUE TITLE
make python_types_to_message and message_to_python_types backwards compatible

### ISSUE THREAD

**Issue by RDWimmers** [cemsbv/nuclei#2]
The typing used in the serialization is not backwards compatible with older API's

Maybe for now, change `PANDAS_DataFrame`  back to  `DataFrame`?

**Comment by ritchie46** [comment]
Are we able to updat the apis?

**Comment by RDWimmers** [comment]
I don't know, the one with the largest legacy is the Google Docs  API. For pilecore, vibracore and gef-model we just have to bump the version I think.

**Comment by ritchie46** [comment]
Bump and redeploy.

**Comment by RDWimmers** [comment]
Yeah, but first the Google Docs API. We use that one in vibracore and pilecore.

**Comment by tlukkezen** [comment]
Maybe to prevent breaking changes now, accept both keys `PANDAS_DataFrame` and `DataFrame` as a pandas.DataFrame?

**Comment by RDWimmers** [comment]
> Maybe to prevent breaking changes now, accept both keys `PANDAS_DataFrame` and `DataFrame` as a pandas.DataFrame?

`message_to_python_types` does that, see: https://github.com/cemsbv/nuclei/blob/4dbcbd13b0ad78d86411897202b1b8014aeace0f/nuclei/utils.py#L250

**Comment by RDWimmers** [comment]
#205
