### ISSUE TITLE
Make Installation section of the README more clear regarding the optional dependencies

### ISSUE THREAD

**Issue by PabloVasconez** [cemsbv/nuclei#207]
With the current description of the `README` of the repo, users using python environment in their local machine will tend to install it by simply using the command: 

```bash
$ pip install cems-nuclei
```
Therefore ignoring the (in this case required) optional requirements provided by the `[client]` option, which will result in an error when using the python code snippets from the samples [(https://nuclei.cemsbv.io/#/sample)](https://nuclei.cemsbv.io/#/sample) .

My suggestion will be to write something like:

**Installation**

To install this package, including the `NucleiClient` library and its dependencies, run:

```bash
$ pip install cems-nuclei[client]
```
To skip the installation of the `NucleiClient` library, in case you do not need it (e.g. [example use cases]), run:

```bash
$ pip install cems-nuclei
```

**Comment by RDWimmers** [comment]
This issue is addressed in commit d1d5490
