### ISSUE TITLE
Polars serialize and deserialize error

### ISSUE THREAD

**Issue by RDWimmers** [cemsbv/nuclei#45]
Serialize and deserialize like below, not possible in polars >= "0.13.6"

```
import polars as pl

pl.read_json(
    pl.DataFrame({"A": [1, 2, 3, 4], "B": [5, 6, 7, 8]}).to_json()
)
```

**Comment by ritchie46** [comment]
Can you make an issue in the polars repo?

**Comment by RDWimmers** [comment]
> Can you make an issue in the polars repo?

Done > https://github.com/pola-rs/polars/issues/3375
